### ISSUE TITLE
update cli to 3.4.0,run error ,please help,tks!

### ISSUE THREAD

**Issue by lauralxj** [smichelotti/Ionic2Course#9]
updated:
``C:\Users\laura\TLGD>ionic serve
? The Ionic CLI has an update available (3.3.0 => 3.4.0)! Would you like to install it? Yes
> npm install -g ionic@latest
✔ Running command - done!

[OK] Upgraded Ionic CLI to 3.4.0! �

Please re-run your command.

Note: You can downgrade to your old version by running: npm install -g ionic@3.3.0

C:\Users\laura\TLGD>ionic serve
? Local plugin @ionic/cli-plugin-cordova has an update available (1.3.0 => 1.4.0)! Would you like to install it? Yes
> npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
✔ Running command - done!
[OK] Upgraded @ionic/cli-plugin-cordova to 1.4.0! �
? Local plugin @ionic/cli-plugin-ionic-angular has an update available (1.3.0 => 1.3.1)! Would you like to install it? Yes
> npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@latest
✔ Running command - done!
[OK] Upgraded @ionic/cli-plugin-ionic-angular to 1.3.1! �
[INFO] Starting app-scripts server: --port 8100 --p 8100 --livereload-port 35729 --r 35729 --address 0.0.0.0 - Ctrl+C to
       cancel
[20:50:30]  watch started ...

Error information:
TypeError: Cannot read property 'name' of undefined
    at Object.eval [as updateRenderer] (ng:///AppModule/MyApp.ngfactory.js:77:45)
    at Object.debugUpdateRenderer [as updateRenderer] (http://localhost:8100/build/main.js:13069:21)
    at checkAndUpdateView (http://localhost:8100/build/main.js:12448:14)
    at callViewAction (http://localhost:8100/build/main.js:12758:17)
    at execEmbeddedViewsAction (http://localhost:8100/build/main.js:12730:17)
    at checkAndUpdateView (http://localhost:8100/build/main.js:12444:5)
    at callViewAction (http://localhost:8100/build/main.js:12758:17)
    at execComponentViewsAction (http://localhost:8100/build/main.js:12704:13)
    at checkAndUpdateView (http://localhost:8100/build/main.js:12449:5)
    at callViewAction (http://localhost:8100/build/main.js:12758:17)
Ionic Framework: 3.2.1
Ionic App Scripts: 1.3.7
Angular Core: 4.1.0
Angular Compiler CLI: 4.1.0
Node: 6.10.3
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36

**Comment by smichelotti** [comment]
Which version of the code base are you running?

**Comment by lauralxj** [comment]
The latest version of the code (for 3.2.1 release) can be downloaded at this link here.

**Comment by smichelotti** [comment]
The course code download has been updated for the latest version here: http://cdn.stevemichelotti.com/code/elite-schedule-3.13.2.zip
